name: Java CI With Gradle

on: 
  push:
   branches:
    - test-pipeline

jobs:
  Preparing:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Print the branch name
        run: |
          branch_name="${GITHUB_REF#refs/heads/}"
          echo "This workflow is running on branch: $branch_name"
      
      - name: Install Java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Check Java Version
        run: |
          java --version

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3 

      - name: Verify Gradle version
        run: gradle -v
