name: Java CI With Gradle

on: 
  #push:
   #branches:
    # - test-pipeline
  workflow_dispatch:

jobs:
  print-branch:
    runs-on: ubuntu-latest  # Run on the latest Ubuntu

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Print the branch name
        run: |
          branch_name="${GITHUB_REF#refs/heads/}"
          echo "This workflow is running on branch: $branch_name"